name: Docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build . --file Dockerfile -t session14:latest

    - name: Build static site
      run: docker run --rm --volume="$(pwd):/app" -t session14:latest mkdocs build

    - name: Update site
      run: |
        git pull
        git config --global user.name "Roberto Antelo"
        git config --global user.email "roberto_antelo@hotmail.com"
        git commit -am "Automated site update"
        git push
